Almost working version with server subscriptions

diff --git a/bin/list-gradle-jars b/bin/list-gradle-jars
--- a/bin/list-gradle-jars
+++ b/bin/list-gradle-jars
@@ -3,9 +3,24 @@
 BIOMINE_TV_BIN="$(dirname $0)"
 BIOMINE_TV_ROOT=$(readlink -f $BIOMINE_TV_BIN/..)
 
-cat $BIOMINE_TV_ROOT/.classpath \
-| grep .gradle/caches/ \
-| sed 's/ /\n/g' \
-| grep '^path=' \
-| sed 's/path="//' \
-| sed 's/"$//'
+DEPS_FILE="$BIOMINE_TV_ROOT/dependencies"
+if ! [ -e "$DEPS_FILE" ]; then
+    echo "Generating list of required 3rd party jars..."
+    cd "$BIOMINE_TV_ROOT"
+    gradle deps || exit 1
+    echo "Done generating dependencies"
+fi
+
+if ! [ -e "$DEPS_FILE" ]; then
+    echo "Failed generating list of dependencies" >&2
+    exit 1
+fi
+
+cat "$DEPS_FILE"
+
+# cat $BIOMINE_TV_ROOT/.classpath \
+# | grep .gradle/caches/ \
+# | sed 's/ /\n/g' \
+# | grep '^path=' \
+# | sed 's/path="//' \
+# | sed 's/"$//'
